title: Utah County 45th Precinct
description: By creating and contributing to this project we intend enable delegates and citizens of the 45th precinct to find and publish information relevant to our community this election year. However, more important than party victories is assuring that our neighborhood is adequately organized and represented.
